##############################################################################
# Global configuration--parameters used in multiple scripts
##############################################################################

# inputdir defines the directory containing the prepared VCF and .summary files
inputdir: "/lustre/scratch119/casm/team294rr/mn7/mutModel/modelA"

# parentdir defines the parent directory containing this repository, output directories, reference data, etc.
parentdir: "/lustre/scratch119/casm/team294rr/mn7/mutModel/modelA"

# mac defines the minor allele count (or frequency) of variants to examine, provided the
# appropriately named directory exists containing the summarized VCF tables
# valid assignments depend on which summary files have been created by
# vcf_to_summary.pl script:
# eg. singletons, common (all variants with MAC>10), other custom
mac: "rare"

# adj defines number of bases upstream/downstream per motif
adj: 7

# bin_scheme variable defines how motifs are counted. Must be set to one of 3 options:
# "all" (count across entire chromosome), "fixed" (fixed-width windows of size binw), "band" (use geimsa-staned banding)
bin_scheme: "all"

# binw defines the width of fixed bins in base pairs
binw: 1000000

# R libpath for log_mod.r
libpath: "~/R-3.6.1"

# Random seed
rseed: 36087318

# Define location and naming convention of raw input vcfs, if we are using the
# 'makecopy' option in vcf_to_summary.pl
# rawvcfext defines the suffix of the raw vcfs we want to copy into inputdir
rawvcfdir: "/lustre/scratch119/casm/team294rr/mn7/mutModel/gnomad_v3"
rawvcfext: "gnomad.v3.1.1.vcf.gz"

# set flags for which files to output when running augment_summary.pl script
count_motifs: TRUE
expand_summ: TRUE
